# Generated by Django 4.0.3 on 2022-03-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award_app', '0003_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(null=True),
        ),
    ]
